### ISSUE TITLE
container restarts regularly after update to 2.24.0

### ISSUE THREAD

**Issue by useib** [pkuehnel/TeslaSolarCharger#1060]
Container "pkuehnel/teslasolarcharger:latest" restarts regularly after update to 2.24.0. 

[teslasolarcharger.log](https://github.com/pkuehnel/TeslaSolarCharger/files/13859028/teslasolarcharger.log)

**Comment by pkuehnel** [comment]
There are no errors in your logfile and TSC restarts once per hour. Does not seem like TSC initiates the restart.
