### ISSUE TITLE
Home Battery min SoC not reached but car is charged with PV power 

### ISSUE THREAD

**Issue by gjuecat** [pkuehnel/TeslaSolarCharger#1098]
Home Battery min SoC set to 70%
actual SoC of Home Battery = 20%
car was chrged the whole day with solar power

as I can remeber this topic worked for me all the time but not since approx. 1 week. Do you have some hints what I should check within my installation?

Thanks and best regards

**Comment by pkuehnel** [comment]
As far as I know I did not change anything in that region for a few months. Please send me a screenshot of your Home Battery settings and a screenshot of the Solar values in the homepage of TSC including all car details while the car is charging but should not. Note: The car details contain your car location, which is irrelevant for me.

**Comment by gjuecat** [comment]
Car details from Teslamate or somewhere else?

**Comment by pkuehnel** [comment]
At the homepage of TSC open the "more car details" section:
![Screenshot_20240127-212751~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/35361981/ccdc3286-9e93-43b6-8534-ca7d53a90f47)

**Comment by gjuecat** [comment]
![Screenshot_20240128_115524_Chrome](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/83f124f0-f5c3-4f8f-9e21-60f14c2beb44)
![Screenshot_20240128_115534_Chrome](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/782a7f37-9af9-462a-a6e0-2f3216caa43e)
![Screenshot_20240128_115540_Chrome~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/66cd62e2-79fb-484e-851b-c48dfc6afb71)
![Screenshot_20240128_115546_Chrome~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/11848485-7a12-4466-bc74-72c12ec2f600)
![Screenshot_20240128_115603_Chrome~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/24219395/b568bf52-b113-43cb-b4a5-15f4e1862e06)

**Comment by pkuehnel** [comment]
What's your configured home battery goal charging power?
![Screenshot_20240131-184332~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/35361981/9e7fa23d-4183-436e-b2d7-6cb2e9ec8f3c)

**Comment by martin-eberle** [comment]
I'm having the same issue right now. Worked fine until about yesterday, when I updated to TSC v2.24.5.

**Comment by pkuehnel** [comment]
@martin-eberle which version did you use before updating?

**Comment by martin-eberle** [comment]
> @martin-eberle which version did you use before updating?

It pretty sure was at least v2.24.2, maybe it already was v2.24.3 or v2.24.4.

**Comment by gjuecat** [comment]
my Home Battery Goal charging power was set to 3000 W
now I changed to 7000W

**Comment by pkuehnel** [comment]
@gjuecat With 3000 Watt set, the TSC did exactly what it should do - reserved 3000 Watt for charging your home battery.

**Comment by gjuecat** [comment]
@pkuehnel thanks for clarification, didn't look at the Battery Goal charging power
