### ISSUE TITLE
Inverter power URLs with "localhost" ignore the port

### ISSUE THREAD

**Issue by d28b** [pkuehnel/TeslaSolarCharger#1150]
In version 2.24.7, when configuring the inverter power URL to any of
```
http://localhost:80/power
http://localhost/power
http://127.0.0.1:80/power
http://127.0.0.1/power
```
TeslaSolarCharger makes a request to
```
http://localhost:7190/power
```

Workaround: use a non-local IP address, e.g.
```
http://192.168.1.100:80/power
```

**Comment by pkuehnel** [comment]
That's an interesting behavior, I will investigate that. Note: localhost inside a container is always the container itself, not the host. Nevertheless the selected port should be used.

**Comment by pkuehnel** [comment]
Should be irrelevant now.
