### ISSUE TITLE
mqtt port configuration issue

### ISSUE THREAD

**Issue by bjv** [pkuehnel/TeslaSolarCharger#1151]
Hi, as from the code I can see that the mqtt port should be extracted from the mqtt server string if it is given in format "ip:port".
But if I set it to 192.168.178.39:1881
I can find the following error in log:
  teslasolarcharger    | MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host '192.168.178.39:1881:1883'.
and the ui is telling me:
 Mqtt Client is not connected

is this a known issue?

**Comment by pkuehnel** [comment]
Is not known, will look into it, but will take about a week I think.

**Comment by pkuehnel** [comment]
Should be fixed now
