### ISSUE TITLE
GUI Immprovement: additional Buttons to set car SOC from TSC GUI

### ISSUE THREAD

**Issue by soulfire89** [pkuehnel/TeslaSolarCharger#1175]
Hey,

it would be nice if there will be buttons in a future version, to change car SOC directly from the TSC GUI. 
Right now a have a standard SOC when arriving at home (50%), because I charge my car at work. But when there are more days with homeoffice i need to adjust car SOC allways first within the Tesla APP.

BR, Armin

**Comment by pkuehnel** [comment]
That will work when https://github.com/pkuehnel/TeslaSolarCharger/issues/325 is fixed. In the next releases, it will be possible to charge non Tesla cars as well. As not all cars support a soc limit, there has to be a soc Limit input in TSC, on Teslas changing this will also change the soc limit in the car.
