### ISSUE TITLE
Issue with Tesla Token? TSC not able to initiate charge.

### ISSUE THREAD

**Issue by TheKingNL** [pkuehnel/TeslaSolarCharger#1282]
I just did a complete refresh of TSC on Docker. (Because I was getting below issue after an upgrade.) I keep getting the following error in TSC;

_You did not request a Tesla Token, yet.
Possible solutions:
Open the Base Configuration and request a new token. Important: You need to allow access to all selectable scopes._

I did provide a Token after the install and TeslaMate graphs are working. TSC also found my car and it can read SoC. It does not start to charge however.

When I open the base configuration page in TSC I have no option to request new tokens. 

Does this has to do with the owner API vs Fleet API?

Or did I miss something else..?

**Comment by pkuehnel** [comment]
There should be a button to request a token.

![Screenshot_20240601-174030~2](https://github.com/pkuehnel/TeslaSolarCharger/assets/35361981/32bb7ed4-742a-4083-b005-b71f2268828f)

**Comment by TheKingNL** [comment]
Thanks @pkuehnel Turns out that Edge was the issue. Somehow it was not displaying the new version of the pages but the old version which did not have this button. It did provide the correct SoC etc so it was a bit odd. Tried it in Chrome now and I was able to add the token.
