### ISSUE TITLE
Cannot change car configuration via http-PUT anymore

### ISSUE THREAD

**Issue by BillGOH** [pkuehnel/TeslaSolarCharger#1301]
I used a script like the following to change charge mode via openHAB:

`curl -X 'PUT' 'http://192.168.202.4:7190/api/Config/UpdateCarConfiguration?carId=1' -H 'accept: */*' -H 'Content-Type: application/json' -d '{ "chargeMode": '$1', "minimumSoC": 30, "latestTimeToReachSoC": "2023-10-29T07:30:00", "ignoreLatestTimeToReachSocDate": true, "maximumAmpere": 16, "minimumAmpere": 4, "usableEnergy": 75, "shouldBeManaged": true, "shouldSetChargeStartTimes": false, "chargingPriority": 2 }'`

However, since latest updates of TSC this does not work. Swagger does not show UpdateCarConfiguration anymore. Any reason for that?

Nevertheless, thanks to @pkuehnel for this great software and his efforts!

**Comment by pkuehnel** [comment]
I refactored everything and removed all unused endpoints, Use POST `/api/Index/UpdateCarBaseSettings`. Note: the json you have to post may have changed.

![image](https://github.com/pkuehnel/TeslaSolarCharger/assets/35361981/e575979e-99f4-4d9c-8176-bc4f04ddceb9)

**Comment by BillGOH** [comment]
Thanks for your quick response and help! It works again.

Would love if solution as asked in #840 would be possible.
