### ISSUE TITLE
Removed source is coming back, if it's the last of its kind

### ISSUE THREAD

**Issue by ptar** [pkuehnel/TeslaSolarCharger#1395]
There's a bug in the source handling in the base configuration, if one switches from one kind of source to another

### Description
* Start with a REST and a MQTT source (and let TSC do it's fine job)
* Later, you switch to a Modbus source and remove the REST and MQTT sources
* After a while (next day, after update, ???) the deleted REST and MQTT sources are coming back

### Expected behavior
* Removed sources remain deleted

**Comment by pkuehnel** [comment]
This was due to conversion of old configurations which was done every time a kind had no configurations.
