### ISSUE TITLE
After Update to 2024.20.6 SetChargingAmps failed :edge

### ISSUE THREAD

**Issue by b1ggi** [pkuehnel/TeslaSolarCharger#1420]
Hi, since the car update BLE cannot set charging amps. 

Failed to execute command: car could not execute command: SetChargingAmps failed

bleproxy host restart, repairing does not work. 

I am running :edge tsc, i tried :latest and :edge bleproxy

Ble wake call works though

**Comment by pkuehnel** [comment]
Very likely a bug in the car's firmware. The charging current can not be Set via the Tesla API as well, correct?

**Comment by b1ggi** [comment]
I can test this evening

**Comment by b1ggi** [comment]
Yes same with ble disabled, only api (156 set amp api calls)

**Comment by pkuehnel** [comment]
Sorry I meant the Tesla App, not API. The Official Tesla App also can not change current.

**Comment by pkuehnel** [comment]
Issue is fixed with Tesla firmware 2024.26.7

**Comment by pkuehnel** [comment]
Looks like the update does not solve the issue for everyone.

**Comment by b1ggi** [comment]
.8 solved it for me just now

**Comment by pkuehnel** [comment]
Some others also claimed that after an update from .6 to .7 solved the issue, so looks like an update solves the problem. Unfortunately, a software reinstall from the service menu does not help (at least not for me).

**Comment by DerHexer** [comment]
This morning I started charging (combined with anprobably unrelated reboot of my BLE RPi).
As everything looked good last evening, it currently (for me) is fixed to command my Tesla via TSC as well.
The test-setting to 7A works, as well as automatic solar-based charging.
As mentioned above, version .7 introduced it and one reboot of my M3 2021 seems to have fixed it. YMMV, but maybe not all people with this issue tried a reboot yet and for some it helps too 🤷‍♂️

**Comment by pkuehnel** [comment]
Looks like I found a solution. What you need to do: Disconnect the car charger, sit in the car, switch off the Bluetooth of your phone. Make sure that no BLE enabled phone, Key Fob,... is around. Note: BLE has a connection radius of > 20 meters, so best would be to disable Bluetooth of all phones and remove the battery from the key fob. Then restart the car by pressing both scroll wheels, wait for the car to reboot (I waited an additional minute after the navigation screen came back), enable Bluetooth on your device. Now it should work again.

**Comment by b1ggi** [comment]
Nice find, unfortunately i cant test/verify it anymore, may be useful for future maybe

**Comment by DerHexer** [comment]
Well, it‘s me again. I had to reboot my Tesla due to a black screen yesterday evening.
Unfortunately today I noticed that my previous fix no longer seems to be working. I am back to being unable to set amps via app or TSC.
Followed the recommended steps by pkuehnel multiple times. Powered of the BLE Rpi, turned off iPhone BT. Unfortunately it’s not working for me.

**Comment by b1ggi** [comment]
I had the bug again after update to 2024.26.8. rebooting without ble in range did not help. I reported the bug to Tesla in the App, they called me and asked about it. They acknowledged its a bug on their side, no estimation when fixed. Then suddenly the bug disappeared without updating or doing something specific.

**Comment by pkuehnel** [comment]
Fixed in Tesla Firmware 2024.32.3
