### ISSUE TITLE
Usability improvement: Add space below Submit-Button on Base-Configuration page

### ISSUE THREAD

**Issue by ralphsiegert** [pkuehnel/TeslaSolarCharger#1452]
On my IPhone the submit button is very close to the lower end of the display and sometimes it takes 2-3 attempts to press it properly that it saves the values. The task switcher from IOS is also very close, so I think this could also interfere with the button and my fingers. 
I suggest to add a padding below or just 2 <BR> below the button. 

![IMG_197CD11C37C6-1](https://github.com/user-attachments/assets/0af7f383-279e-476c-bb23-32444b3d2cc4)

Additionally, I think it would be good to lock the button after I hit it or to give visual feedback that I hit it (this looks like a different story, I add this separately if you want to).

**Comment by pkuehnel** [comment]
Yes, please add another issue vor adding visual feedback, thanks.

**Comment by pkuehnel** [comment]
Will be fixed in the next version
