### ISSUE TITLE
Add visual feedback after pressing the submit button on base configuration page

### ISSUE THREAD

**Issue by ralphsiegert** [pkuehnel/TeslaSolarCharger#1453]
This was from a different issue:
(Additionally, I think it would be good to lock the button after I hit it or to give visual feedback that I hit it)

As user story I'd say it like this: 

As user I want to see a visual feedback after hitting the "Save"-Button on the bottom of the page to be sure that I hit it properly and to avoid to hit it twice. 

The save Button on Main App page e.g. changes to a "Save"-State that would already solve it.

**Comment by pkuehnel** [comment]
will be fixed in the next version
