### ISSUE TITLE
Grid Power isn't avaivable

### ISSUE THREAD

**Issue by DomiSanNo1** [pkuehnel/TeslaSolarCharger#1467]
Grid Power doenst get states. I've changed nothing in the config.
HomeAssistant gets the values, TSC not.

![image](https://github.com/user-attachments/assets/a5e725e7-a101-4c65-8691-1bd1726066fb)
![image](https://github.com/user-attachments/assets/09e2a615-0536-4e9e-8824-ed5e4c7acb33)

**Comment by pkuehnel** [comment]
Looks like you are using the SMA Plugin. As SMA sends the power data via multicast very likely a network change is responsible for that:
 * Do you have a new switch in the network?
 * Do you have a new router in the network?
 * Did you change any thing with the cabling?
 * Did you switch your OS from Linux to Windows? On Windows the SMA plugin is not supported

**Comment by pkuehnel** [comment]
I am pretty sure it is a network problem. If you cannot fix it, you can define fix IP Adresses in the SunnyPortal, where the messages should go to. Note: You need to add all your inverters and your device with the SMA plugin.

**Comment by DomiSanNo1** [comment]
I've filled the unicast fields at the sunnyportal (inverter + TSC Server). What do i have to configure in TSC? I get no values.

**Comment by pkuehnel** [comment]
Nothing, it should just work. What does the SMA Plugin Log say?

**Comment by DomiSanNo1** [comment]
How can I read it?

**Comment by pkuehnel** [comment]
Is the timestamp of the latest logs correct? Might be in UTC Time. Is there any whitespace character in the URL because TSC says `Requesting string with url http://192.168.1.200:7192/api/CurrentPower/GetPower?`. The last `?` should not be there.
What happens when you open `http://192.168.1.200:7192/swagger` in your web browser? Are you able to get the value there?
![image](https://github.com/user-attachments/assets/244bc020-6d75-4d91-acbe-394a24438adf)

**Comment by DomiSanNo1** [comment]
No I dont 
![image](https://github.com/user-attachments/assets/12f9bdb8-9676-46fa-b048-acfcf69d40c0)

**Comment by pkuehnel** [comment]
Then your sma Plugin still does not receive the Power values. There is an issue with your Network. When it is working you should See a new Log entry with the Power values in the SMA Plugin at least once every second.

**Comment by pkuehnel** [comment]
Can you send me a logfile of the SMA Plugin here?

**Comment by DomiSanNo1** [comment]
I can collect the values via HomeAssistant and save them in my MQTT. TSC can read the MQTT data and it works for now. But TSC don't find the HomeManager directly. I reached my personal limit ;)

**Comment by DomiSanNo1** [comment]
The containers in docker looking strange too. What does the "-1" mean?

![image](https://github.com/user-attachments/assets/3e7e7a38-8f7c-43e1-a2d1-0767d615ed56)

**Comment by pkuehnel** [comment]
Normal naming behavior of docker `directory-imageName-number`. The TSC Containers have fixed names defined in the `docker-compose.yml` as some parts of the Readme (e.g. Generate logs) depend on the Container names.

**Comment by pkuehnel** [comment]
So dokumente because your yml is in the Direktory `Dokumente` and -1 because one Container is running. If you would have a second container with the same Service Name it would be -2
