### ISSUE TITLE
UI crash on startup on some devices

### ISSUE THREAD

**Issue by gjuecat** [pkuehnel/TeslaSolarCharger#1643]
since ~3 days I get this error on my PC, on the mobile phone everything is OK
any ideas?

![2024-11-20 21_40_57-TeslaSolarCharger](https://github.com/user-attachments/assets/451e5b12-e95b-4eaa-a76a-a791abfe9fdc)

thx and best regards

**Comment by pkuehnel** [comment]
Which browser are you using, which operating system are you using? If you are on chrome please press F12 after the error occures. You should see a white X with a red background in the top right corner, click on it and send a screenshot of the error details (displayed at the bottom in red background).

**Comment by pkuehnel** [comment]
Did you disable WebAssembly support? How do disable it is described here: https://github.com/stevespringett/disable-webassembly

WebAssembly needs to be enabled for TSC to work.

**Comment by gjuecat** [comment]
I didn't change anything on both PCs. Chrome is started as everytime without an argument. I just tried with Edge and get the same error.
In Chrome it looks like it is on:
![2024-11-23 21_50_49-Clipboard](https://github.com/user-attachments/assets/9ca523f2-b480-4e03-b434-e2b5760c52a8)

**Comment by gjuecat** [comment]
On another Win 11 PC with the same Chrome account everythings works fine,
also on a mobile phone with my Chrome account.
On the other Win 11 PC I added a new account on Windows, used the installed
Chrome but without Chrome Logon and I also get the unhandled error.

Would a Teamviewer or Anydesk Session be OK for you?


Am So., 24. Nov. 2024 um 16:59 Uhr schrieb pkuehnel <
***@***.***>:

**Comment by pkuehnel** [comment]
Ia m afraid I can't help you then. I thought maybe the issue could be reproduced with my chrome where I can use a debugger. But if it is working on another win 11 PC, also with Chrome I very likely cannot reproduce the issue with my Chrome (TeamViewer or AnyDesk would not help, as I need my dev environment). Try reinstalling Chrome and delete all chrome related stuff. (Not sure if this is up do date: https://support.google.com/chrome/thread/29816481/how-do-i-fully-uninstall-chrome?hl=en)

**Comment by pkuehnel** [comment]
Please provide feedback if and how you could resolve the issue.

**Comment by gjuecat** [comment]
I don't know why but now it works again on both (Win 10 and Win 11 PC) wirhout doing anything. Maybe a Chrome Update?? Windows Update isn't possible because they are not the same on Win 10 and Win 11.
