### ISSUE TITLE
Test BLE access - 1A

### ISSUE THREAD

**Issue by gigich** [pkuehnel/TeslaSolarCharger#1647]
Könnte man nicht den Testbutton ändern von 7A nach 1A?
Das hätte den  Vorteil dass man danach in der Tesla App mit 1A manuell den Ladevorgang starten könnte und dann auch hochregeln. Runter geht ja leider unter 6A nicht. 

Der Change wäre ja wahrscheinlich relativ einfach umsetzbar und würde einen tollen Mehrwert bieten. 

Danke fürs prüfen

**Comment by pkuehnel** [comment]
Not that easy as going over 5A needs a double request. This could result in issues that take ~20 seconds to resolve, so using anything below 5A can not be used to test BLE access. But TSC accesses the BLE API via a REST API. You can send these commands by yourself. Just open `http://<BLEcontianerIP>:7210/swagger` and you will see the documentation of the API.
