### ISSUE TITLE
LoadBalancing-Feature: MaxAmp for 2 cars

### ISSUE THREAD

**Issue by haexpo** [pkuehnel/TeslaSolarCharger#188]
It would be helpful, to be able to set a MaxAmp (e. g. 16A) that can not be exceeded while charging both cars at the same time.

**Comment by pkuehnel** [comment]
What's your main goal with this? Prevent charge stop of the seceond car? Or reducing combined load?

**Comment by haexpo** [comment]
The main goal would be to reduce the combined load. I wouldn't have to use the load balancing feature that comes with the wall connectors V3 which may interferes with TeslaSolarCharger (haven't tested that).

**Comment by pkuehnel** [comment]
You can use that feature without issues since [v1.8.0](https://github.com/pkuehnel/TeslaSolarCharger/releases/tag/v1.8.0)

**Comment by pkuehnel** [comment]
Please reopen the issue if you have problems with Loadbalancing of your Wall Connector
