### ISSUE TITLE
Float values for correction factors

### ISSUE THREAD

**Issue by schneefloh** [pkuehnel/TeslaSolarCharger#283]
My Victron system presents some modbus values like battery SOC with a factor of 10, e.g. 98% = 980. 
Correction factors only accept decimal values but I need 0.1 in this case.

**Comment by pkuehnel** [comment]
`0.01` is working for me and calculated correctly:

![image](https://user-images.githubusercontent.com/35361981/189189322-4bb98b47-cf41-42a7-babd-5034b272382e.png)


Are you sure you pasted the value in the correct field?

**Comment by schneefloh** [comment]
Yes, I think so. As soon as I hit enter the value reverts to 1. 
Even tried on different browsers and using the latest 2.5.0.
![Zwischenablage01](https://user-images.githubusercontent.com/113058377/189195647-56b3bcbe-d80a-4b2a-9559-2b8eaa948c98.png)

**Comment by schneefloh** [comment]
addition: if I type 1.0 and hit enter it reverts to 10?

**Comment by pkuehnel** [comment]
But it does not change when you leave the field? Only after submitting?

**Comment by pkuehnel** [comment]
Which hardware and which OS do you use? What is the language of your OS? Could you please upload the logs of the `teslasolarcharger` container?

If you use the latest `docker-compose.yml` you can create a lofgile with
```
docker logs teslasolarcharger > teslasolarcharger.log
```

If you use an older version of the `docker-compose.yml` you probably have to use a different containername.

**Comment by schneefloh** [comment]
It reverts to a value without dot even when I press tab or click somewhere else.
Docker runs on a Synology NAS with language set to German.
Logfile attached.
Thanks a lot for your help!
[teslasolarcharger.log](https://github.com/pkuehnel/TeslaSolarCharger/files/9530628/teslasolarcharger.log)

**Comment by pkuehnel** [comment]
Ok, then this already happens in the browser and the logs don't help. please change your image to 
``` 
pkuehnel/teslasolarcharger:decimal
```
Does this help (version should be `2.5.1-alpha.0.4`)

**Comment by schneefloh** [comment]
I can confirm everything works as expected in 2.5.1-alpha.0.4 without other changes.
Thanks!

**Comment by pkuehnel** [comment]
You can stay on `:decimal` for now. The bugfix will be in the next release, then you can go to `:latest` again.

**Comment by pkuehnel** [comment]
You knwo can go back to `:latest`.
