### ISSUE TITLE
Charing --> Charging? in log-outputs and also functionnames

### ISSUE THREAD

**Issue by gaborfri** [pkuehnel/TeslaSolarCharger#341]
in the logs i found the following Outputs:

Set Should charge since to early date so car will stop charing.
or
Can not stop charing: Climate on:

is there an typo, or did i missunderstood

**Comment by pkuehnel** [comment]
Typos.

**Comment by pkuehnel** [comment]
Wow six times the same typo, will be fixed in next version.
