### ISSUE TITLE
using own mqtt with authorization

### ISSUE THREAD

**Issue by gaborfri** [pkuehnel/TeslaSolarCharger#362]
i am not able to connect my own mqtt server. the server itself is configured in the settings, but only as URL (the port is added automatically). I seem to be missing the possibility to specify the user and password

**Comment by pkuehnel** [comment]
What exactly do you mean with URL?
You can add your MQTT server + port (e.g. `192.168.1.50:1883`), your username + password for authentication in the MQTT server + Topics for grid power, inverter power (not needed just for displaying the value), and optional your home battery charging/discharging power and home batter soc:
![image](https://user-images.githubusercontent.com/35361981/194318140-32fce79e-c65b-40e5-921b-b9ecaedd21ed.png)

**Comment by gaborfri** [comment]
i mean not this setting. at the very end of the configuration part called "Mosquito servername". Here is only an input for the servername, but no configuration for the username/password.
At the end i get the following error message in my mosquitto log:
Client TeslaSolarCharger disconnected, not authorised

gabor

**Comment by pkuehnel** [comment]
Does TeslaMate support the MQTT server to have authentication?

**Comment by pkuehnel** [comment]
Seems to be irrelevant as no answer in 24 days.

**Comment by idominiki** [comment]
Hi @pkuehnel 
I have an MQTT Server running on my home assistant which teslamate connects to. Is it possible to using this MQTT for TeslaSolarCharger? 
I don't have the settings to enter MQTT username and password in the base settings.
Thanks
Dominik

**Comment by pkuehnel** [comment]
This is currently not possible.

**Comment by pkuehnel** [comment]
https://github.com/pkuehnel/TeslaSolarCharger/issues/673

But this won't be possible in the nearer future.

**Comment by BillGOH** [comment]
First of all, thanks for this great software.

Unfortunately I am running (a very busy) MQTT broker on my openHAB server with authentication (which Teslamate uses; and then openHAB uses the data). It would be nice if one could choose another MQTT server (with credentials), not the "built in" one.

**Comment by pkuehnel** [comment]
You can change the MQTT server but (for now) credentials are not support.

**Comment by BillGOH** [comment]
Thank you for your quick response. I added `allow_anonymous true` to the openHAB MQTT server config (= mosquitto) and it works fine now!
