### ISSUE TITLE
ChargingService:  "Amps to set" is to high

### ISSUE THREAD

**Issue by AexKR** [pkuehnel/TeslaSolarCharger#363]
Hi,
Tesla Solar Charger is up and running (latest setup yesterday, 05.10.2022 based on docker-compose, V3.3 example.  Car Settings are done (min 5A; max 12A)  + "Use TeslaSolarCharger: active" --> PV Only. Url used to provide value for Watt --> works. 

![image](https://user-images.githubusercontent.com/35378795/194320970-bec0685f-b264-4cd8-a7e1-07c524371200.png)

Value "Amps to set: 21" seems to be wrong...Charging is set to 12 A (as definded in the car settings for max). I would expect 9 A

It looks like a calculation of last value (12A) + "Amp to control: 9A" --> 21A

 
![image](https://user-images.githubusercontent.com/35378795/194322300-b7ffc456-e95f-46e0-865b-fe5922f2bd98.png)

**Comment by AexKR** [comment]
![image](https://user-images.githubusercontent.com/35378795/194327443-ddef8d15-3716-4d36-80ff-252b0b8707e5.png)

**Comment by pkuehnel** [comment]
Looks like you did not use the correct URL for grid power.
This value:
![image](https://user-images.githubusercontent.com/35361981/194329007-11a76969-0909-48c6-9b2b-6e7f247ccd2a.png)
needs to be the power value going to the grid (smart meter), not your inverter power. So if you are sending power to the grid this values is green and turns red if you are consouming power from the grid:
![image](https://user-images.githubusercontent.com/35361981/194328887-5110dff1-4b49-45be-9197-9582851eeab1.png)

In your example the value is probably green displaying 2176 Watt (first line in your logfile). As TeslaSolarCharger thinks, that you are sending 2176 Watt to the grid although already charging with 2772 Watt it adds the 2176 Watt to the already charging 2772 Watt.

**Comment by AexKR** [comment]
Thanks for clarification! I will add the information about consumption.
