### ISSUE TITLE
Exclamation mark in status

### ISSUE THREAD

**Issue by VinciSC** [pkuehnel/TeslaSolarCharger#380]
Hi,
since updating from 2.7.5 to 2.7.7 I see an encircled exclamation mark below the current SoC and charging power (second line in picture below). 
![grafik](https://user-images.githubusercontent.com/109548296/196164661-d265984a-82ce-4097-a576-a4197f3c6a90.png)
No idea what is wrong. 
Any hint how to solve or what to check?
Thanks
VinciSC

**Comment by VinciSC** [comment]
Checked TeslaMate, no red exclamation mark there. Scrolled down in TSC, the line "Car Healthy" was empty.
It looks like the car charged during afternoon (SoC from 56 to 63%) while the exclamation mark was present.
Restarted all containers now. The exclamation mark is gone and "Car Healthy" reports true.
Thanks for advice!
Regards
VinciSC

**Comment by pkuehnel** [comment]
Issue is probably that the bool value defaults to false. Will be fixed with https://github.com/pkuehnel/TeslaSolarCharger/issues/381
