### ISSUE TITLE
Allow smart meter values to be json formatted

### ISSUE THREAD

**Issue by gjuecat** [pkuehnel/TeslaSolarCharger#41]
whats has to be the format and data of this REST endpoint? 

I'm using a KNX counter for energy from or to the grid, so the counter itself has no IP interface (but I'm using MQTT via Gira Homeserver to get the data to IP). 
Now I'm thinking about some other tools if they are able to provide the information as REST endpoint. I'm not so familar with REST endpoint - so I need some information how I have to provide the data.

A possibilty which is already realised would be a HTTP call which delivers such data: 
{"request": {"method": "get", "key": "CO@13_3_0"}, "code": 0, "type": "call", "data": {"value": 14.0}}

The value would contain information how much energy comes or is deliverd to grid.

thx

**Comment by pkuehnel** [comment]
Currently only integer values are supported. I will add an option to parse json data.

**Comment by pkuehnel** [comment]
@gjuecat What does the value 14.0 represent? 14 Watt curently going to the grid? How would the json look like, if 14 Watt are coming from the grid?

**Comment by gjuecat** [comment]
{"value": -1196.0} means that my house takes 1196.0 watt **from** the grid
{"value": 889.0} means that my house delivers 889.0 watt **to** the grid

**Comment by gjuecat** [comment]
@pkuehnel works perfect - thank you

**Comment by pkuehnel** [comment]
@gjuecat You can now switch back to `:latest` tag.

**Comment by gjuecat** [comment]
Hi,
I upgraded to the latest version but now I'm not able to get power to grid with method from this issue.
Do I have to use environment variable? I din't try because on base configuration there is the possibility to enter the JSON result type $.data.value like you mentioned in this issue before.
![2023-02-06 10_57_55-Base Configuration](https://user-images.githubusercontent.com/24219395/216941931-aea0ec5f-6c06-45c7-808b-b2afe0dcd2b7.jpg)

**Comment by gjuecat** [comment]
one more question: Home Battery is set to NONE but on the Overview page it is always mentioned in red:
![2023-02-06 22_38_23-Tesla Solar Charger](https://user-images.githubusercontent.com/24219395/217094056-1c2345d8-b9c8-4001-9f0f-12020e8e8314.jpg)
Is this OK or is there something wrong?

**Comment by pkuehnel** [comment]
This is currently an issue... Please toggle through all options (rest, modbus,MQTT) and delete every URL and so on...

**Comment by gjuecat** [comment]
I changed https to http and now except battery power everthings gets correct values. Any ideas why battery power is not working? Answer from http request is the same like others and JSON pattern is also defined as "$.data.value"

**Comment by pkuehnel** [comment]
Do you have self-signed certificates? If you have officially signed certificates, https should also work.

Are you sure you have not set any field (like xml path, MQTT Topix or something like that)?

**Comment by gjuecat** [comment]
for Home Battery only REST and JSON Result type. XML path is empty and no MQTT used

**Comment by pkuehnel** [comment]
Could you please again send me your logs but please nor the Json formatted, just the plain logs like described [here](https://github.com/pkuehnel/TeslaSolarCharger#generate-logfiles) .

**Comment by gjuecat** [comment]
[teslasolarcharger.log](https://github.com/pkuehnel/TeslaSolarCharger/files/10674855/teslasolarcharger.log)

**Comment by pkuehnel** [comment]
Looks like something is wrong with your URL. Maybe invisible characters, returns, or spaces or something like that?

**Comment by gjuecat** [comment]
I used copy paste for all inputs and only changend one number within the URL. The answer from all of them has the same format and if I use the battery power URL in browser there‘s the correct value returned

**Comment by gjuecat** [comment]
HomeBatteryPowerInversion URL is set to 0, but also 1 doesn't work

**Comment by pkuehnel** [comment]
Could you please send me your baseConfig.json from your docker volume? But attention, everything you configured (including database password is in there). You can upload it [here](https://nextcloud.pkuehnel.de/s/RWxe4MWC9LDRcL2), so I am the only one who can see the file.

**Comment by gjuecat** [comment]
file is online

**Comment by pkuehnel** [comment]
> HomeBatteryPowerInversion URL is set to 0, but also 1 doesn't work

Ah this is your problem. I thought this was a typo... HomeBatteryPowerInversionURL needs to be set to empty... There you can insert an URL if your home battery always sends positive values but with another URL you can see if the battery is charging or discharging. Just remove the 0 there.

**Comment by gjuecat** [comment]
thanks, that was the solution
