### ISSUE TITLE
Grid Power Buffer in Baseconfig: only positive inputs possible

### ISSUE THREAD

**Issue by MalteSchm** [pkuehnel/TeslaSolarCharger#521]
When setting the Grid Power Buffet on my android Tablet using the Samsung keyboard no minus sign is shown on the keyboard,  I.e. negative value cannot be set

**Comment by pkuehnel** [comment]
I just tried it with my Google Pixel phone (using [SwiftKey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey&hl=de&gl=US) as keyboard) and it works fine.

On my desktop, I can even use the down key (as no minimum value is set):
![image](https://user-images.githubusercontent.com/35361981/211148134-29ee3764-0257-4f61-a4df-d334d1c697da.png)

Could you please try the first input field on [this page](https://thepaciellogroup.github.io/AT-browser-tests/test-files/input-number.html): 
![image](https://user-images.githubusercontent.com/35361981/211148522-093a06eb-1bac-453d-ab83-4dc69204cb48.png)

I don't have a Samsung device to debugging is not possible for me.

**Comment by pkuehnel** [comment]
Looks like this is a Samsung specific issue on JavaScript: Look at the first answer [here](https://stackoverflow.com/questions/21677695/input-type-number-not-possible-to-insert-negative-numbers-on-mobile-phone)

**Comment by MalteSchm** [comment]
Agreed this is my finding.
I'll update these values with another device then. 

Btw:
While testing I discovered that the correction factor seems not to use the JS number type and the full keyboard is shown

**Comment by pkuehnel** [comment]
Or you just install Switft Key and use that for these changes. Changing keyboard are three clicks (at least on my device).

Yes this is because these fields are normal text fields (as this is my first project with a web UI I didn't know how to do it better that time, especially with country based `.` or `,` as decimal separator).

**Comment by pkuehnel** [comment]
One last question: Is there a `-` on your keyboard e.g. in the Min SoC field on the main page (is not shown if you are in maximum power mode):
![image](https://user-images.githubusercontent.com/35361981/211191566-0fd99466-24de-47b3-a2bc-0b0b78ce5a53.png)

**Comment by MalteSchm** [comment]
No, same keyboard is used here I.e. no minus sign
