### ISSUE TITLE
Loss of data on "Total charged solar energy" after update

### ISSUE THREAD

**Issue by VinciSC** [pkuehnel/TeslaSolarCharger#684]
Hi,
just did the update to 2.14.0 (using the commands `docker-compose pull` and `docker-compose up -d`) and observed that the displayed values regarding "Total charged solar energy", "Total charged grid energy" and the corresponding cost seem to be lost as the values are displayed as zero.
I checked the volumes defined in my docker-compose.yml and do not see a difference to the yml in the documentation.
Any hint on the root cause and how to prevent the loss?
Thanks and best regards!
VinciSC

**Comment by pkuehnel** [comment]
Could you please upload your complete log file of your TSC container and give me a Timestamp when you did the upgrade?

Please use [this link](https://nextcloud.pkuehnel.de/s/WcbF94aqSHNKCSE) for uploading, as the logs may contain private data (e.g., longitude/latitude of your geo-fence).

**Comment by VinciSC** [comment]
logfile has been uploaded.
log starts yesterday 13:20 and already shows Version 2.14.0, no data left from previous 2.13. I saw some entries regarding an issue w/ mqtt. 
I'm not sure about exact time of update but it was around noon.

**Comment by pkuehnel** [comment]
Will look into it… logs are deleted after update as an update recreates the container. As long as you did not recreate after the issue, I should find it.

**Comment by pkuehnel** [comment]
Strange… I can not see anything wrong. Could you also upload all `configs/TeslaSolarCharger.*` (should be 1–3 files) in your Docker volume? Please stop the TSC container before that.

**Comment by VinciSC** [comment]
Done. 

 

Please ignore the zip, this was created with running containers ☹ Stopped the container afterwards and copied the *.db fiel again. 

 

Von: pkuehnel ***@***.***> 
Gesendet: Dienstag, 21. März 2023 12:46
An: pkuehnel/TeslaSolarCharger ***@***.***>
Cc: VinciSC ***@***.***>; Author ***@***.***>
Betreff: Re: [pkuehnel/TeslaSolarCharger] Loss of data on "Total charged solar energy" after update (Issue #684)

 

Strange… I can not see anything wrong. Could you also upload all configs/TeslaSolarCharger.* (should be 1–3 files) in your Docker volume? Please stop the TSC container before that.

**Comment by pkuehnel** [comment]
Hmm… No relevant data in the database as well. In future releases, I will make a backup copy of the database before updating the database schema. Do you have a backup of the database before the update to 2.14.0? If so, I could test an upgrade with your database.

**Comment by VinciSC** [comment]
Just noticed that there is an additional volume present in my container. Besides the 5 named volumes defined in the docker-compose.yml there is an anonymous volume created and used by mosquito, see screenshot I just uploaded on your nextcloud.

I have no idea why this volume is created, double checked my docker-compose.yml, looks OK:

 

services:

[..]

  mosquitto:

[..]

    volumes:

      - mosquitto-conf:/mosquitto/config

      - mosquitto-data:/mosquitto/data

[..]

volumes:

  mosquitto-conf:

  mosquitto-data:

**Comment by VinciSC** [comment]
> [...]. Do you have a backup of the database before the update to 2.14.0? If so, I could test an upgrade with your database.

Sorry, no backup of the config folder, I'm only buping the postgres db of TSC ...

**Comment by pkuehnel** [comment]
From now on, with each update, a backup of the original database is created in the same directory. I also added an option to close all open connections to the SQLite database more aggressively. This results in slightly reduced performance but better error handling.

@VinciSC Please check if the issue persists, if so reopen the issue and let me know, I will create another Nextcloud link, so I can test with your database.

**Comment by VinciSC** [comment]
Recently updated to 2.14.1. This time the values for "Total charged solar energy" and "Total charged grid energy" remain as before the update. Backup of the db is created automaticly during update.
SO this look good, thanks!
