### ISSUE TITLE
car is charging by PV but not visible in GUI

### ISSUE THREAD

**Issue by merlinfive** [pkuehnel/TeslaSolarCharger#711]
Hi , updated this morning as recommended , the car start charging by PV (check by Tesla App) but it does not show up in Teslasolarcharger GUI
edit : looks ok post second restart of all containers

![image](https://user-images.githubusercontent.com/101570702/227891909-d3080a23-69fd-42e3-aade-75acd231ed09.png)

**Comment by pkuehnel** [comment]
As there is no home icon below your car name, it is not recognized being at home. This is currently an issue when restarting Mosquitto and TSC without (or after) restarting TeslaMate. Restarting the TeslaMate container alone would resolve that issue. Is also already fixed. Fix will be released in 2.15.0.

**Comment by merlinfive** [comment]
strange behaviour and recognized wrong timestamp in smaplugin.log (2 hours behind teslacharger.log) sometimes charge does not start

**Comment by pkuehnel** [comment]
TimeStamp is default UTC. In TeslaSolarCharger you probably set the Environment variable for the `Timezone`. This is not needed in the plugins as time has no effect, just for logging output.

> sometimes charge does not start

Charging only starts if there is enough power for at least 5 minutes. If you open the details of a car, the timestamp is displayed, when charging will start/stop.

**Comment by merlinfive** [comment]
ok ,  

> "In TeslaSolarCharger you probably set the Environment variable for the Timezone. This is not needed in the plugins as time has no effect, just for logging output."

 , I was confused , typical I check log files against each other so equal timestamps would make it more clear.

**Comment by pkuehnel** [comment]
I will add a timezone to the log outputs: https://github.com/pkuehnel/TeslaSolarCharger/issues/712

**Comment by pkuehnel** [comment]
Are all other issues resolved?

**Comment by merlinfive** [comment]
I guess , will monitore during day (on vacation)
