### ISSUE TITLE
Min Soc based on weekdays

### ISSUE THREAD

**Issue by pkuehnel** [pkuehnel/TeslaSolarCharger#846]

**Comment by b1ggi** [comment]
Would love that feature

**Comment by BillGOH** [comment]
Feature would be highly appreciated. Not necessary to charge to MinSOC on Saturday and Sunday.

**Comment by b1ggi** [comment]
https://github.com/pkuehnel/TeslaSolarCharger/pull/1294

Possible fix

**Comment by b1ggi** [comment]
https://github.com/pkuehnel/TeslaSolarCharger/pull/1340 feature can be tested with the image tag pkuehnel/teslasolarcharger:weekdaycharging
