### ISSUE TITLE
Make Spotprice available from different Sources

### ISSUE THREAD

**Issue by outrun0506** [pkuehnel/TeslaSolarCharger#918]
Hi,

Currently only EPEX DE is possible as Source for Spot Prices. Would be great if we can select from different Services e.g. aWattar in Austria. They already provide an api via https://api.awattar.at/v1/marketdata

Dokumentation can be found hear: https://www.awattar.at/services/api/

Thanks for considering.

BR
Lukas

**Comment by pkuehnel** [comment]
Should be resolved with fixing https://github.com/pkuehnel/TeslaSolarCharger/issues/851
